// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import type { PrismaConfig } from "prisma";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate) потребує прямого з’єднання; з pooler (Supabase) — DIRECT_URL, інакше DATABASE_URL
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
} satisfies PrismaConfig);
